install.packages("plspm")
library(plspm)
data("spainfoot")
ataque<-c(0,0,0)
defensa<-c(0,0,0)
exito<-c(1,1,0)
rel_fut<-rbind(ataque, defensa, exito)
colnames(rel_fut)=rownames(rel_fut)
innerplot(rel_fut)
bloques=list(1:4,5:8,9:12)
modos=c("A","A","A")
mod_fin=plspm(spainfoot,rel_fut,bloques,modes=modos)
plot(mod_fin)
summary(mod_fin)