tsfilter hp banti= anti, trend(l1)
tsfilter hp batla= atla, trend(l2)
tsfilter hp bbogo= bogo, trend(l3)
tsfilter hp bboli= boli, trend(l4)
tsfilter hp bboya= boya, trend(l5)
tsfilter hp bcald= cald, trend(l6)
tsfilter hp bcaqu= caqu, trend(l7)
tsfilter hp bcauc= cauc, trend(l8)
tsfilter hp bcesa= cesa, trend(l9)
tsfilter hp bcord= cord, trend(l10)
tsfilter hp bcund= cund, trend(l11)
tsfilter hp bchoc= choc, trend(l12)
tsfilter hp bhuil= huil, trend(l13)
tsfilter hp blagua= lagua, trend(l14)
tsfilter hp bmagd= magd, trend(l15)
tsfilter hp bmeta= meta, trend(l16)
tsfilter hp bnari= nari, trend(l17)
tsfilter hp bnort= nort, trend(l18)
tsfilter hp bquin= quin, trend(l19)
tsfilter hp brisa= risa, trend(l20)
tsfilter hp bsant= sant, trend(l21)
tsfilter hp bsucr= sucr, trend(l22)
tsfilter hp btoli= toli, trend(l23)
tsfilter hp bvall= vall, trend(l24)
tsfilter hp bcolombia= colombia, trend(l25)

anti atla bogo boli boya cald caqu cauc cesa cord cund choc huil lagua magd meta nari nort quin risa sant sucr toli vall colombia



gen anticm=ln(anti)

gen anticm=ln(anti)
gen atlacm=ln(atla)
gen bogocm=ln(bogo)
gen bolicm=ln(boli)
gen boyacm=ln(boya)
gen caldcm=ln(cald)
gen caqucm=ln(caqu)
gen cauccm=ln(cauc)
gen cesacm=ln(cesa)
gen cordcm=ln(cord)
gen cundcm=ln(cund)
gen choccm=ln(choc)
gen huilcm=ln(huil)
gen laguacm=ln(lagua)
gen magdcm=ln(magd)
gen metacm=ln(meta)
gen naricm=ln(nari)
gen nortcm=ln(nort)
gen quincm=ln(quin)
gen risacm=ln(risa)
gen santcm=ln(sant)
gen sucrcm=ln(sucr)
gen tolicm=ln(toli)
gen vallcm=ln(vall)
gen colombiacm=ln(colombia)
